---
- hosts: localhost
  become: yes
  gather_facts: true
  tasks:
    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: "/root/Final-DevOps-Project-ABC"
        name: docker.io/mallieswari/abc-technologies-latest-with-ansible
        tag: latest
        push: true
        source: build
      register: build_image_out

    - name: Display build image output
      debug:
        var: build_image_out

    - name: Start a container
      community.docker.docker_container:
        name: abc-container-with-ansible
        image: mallieswari/abc-technologies-latest-with-ansible
        state: started
        ports:
          - "8000:8080"
      register: build_container_out

    - name: Display container start output
      debug:
        var: build_container_out

    - name: Deploying to Kubernetes
      command: "kubectl --kubeconfig=/home/minikubeuser/.kube/config apply -f /root/Final-DevOps-Project-ABC/deployment.yaml"
      register: out

    - name: Display Kubernetes deployment output
      debug:
        var: out
