---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: abc-technologies-deployment
  namespace: abc-tech-namespace
spec:
  replicas: 2
  minReadySeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: abc-tech-app
  template:
    metadata:
      labels:
        app: abc-tech-app
    spec:
      containers:
      - name: abc-app
        image: mallieswari/abc-technologies:latest

---
kind: Service
apiVersion: v1
metadata:
  name: abc-tech-service
spec:
  type: NodePort
  selector:
    app: abc-tech-app
  ports:
  - port: 80        # Cluster port
    targetPort: 8080 # Container port
    nodePort: 30000  # NodePort (optional, Kubernetes will assign one if not specified)#

